version: 2
updates:
- package-ecosystem: cargo
  directories:
    - "/"
    - /cpp
    - /nodejs
    - /parameterized-test
    - /python
  schedule:
    interval: weekly

- package-ecosystem: uv
  directories:
    - /docs
    - /python
  schedule:
    interval: weekly

- package-ecosystem: npm
  directory: /nodejs
  schedule:
    interval: weekly
