version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly

- package-ecosystem: uv
  directories:
    - /docs
    - /python
  schedule:
    interval: weekly

- package-ecosystem: npm
  directory: /nodejs
  schedule:
    interval: weekly

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
