[package]
name = "libloot"
version = "0.27.0"
edition = "2024"
license = "GPL-3.0-or-later"

[dependencies]
crc32fast = "1.4.2"
esplugin = "6.1.3"
fancy-regex = "0.14.0"
libloadorder = "18.4.0"
log = { version = "0.4.26", features = ["std"] }
loot-condition-interpreter = "5.3.2"
petgraph = "0.8.1"
rayon = "1.10.0"
rustc-hash = "2.1.1"
saphyr = "0.0.6"
unicase = "2.8.1"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.61.1", features = ["Win32_Storage_FileSystem"] }

[dev-dependencies]
parameterized-test = { path = "./parameterized-test" }
tempfile = "3.17.1"

[workspace]
members = ["cpp", "ffi-errors", "nodejs", "parameterized-test", "python"]

[profile.release]
debug = "limited"
lto = "thin"

[profile.rel-with-deb-info]
inherits = "release"
opt-level = 2
debug = "limited"
