[package]
name = "libloot_pyo3"
version = "0.25.5"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "loot"
crate-type = ["cdylib"]

[dependencies]
libloot = { path = ".." }
pyo3 = "0.24.0"
