[package]
name = "libloot-ffi-errors"
description = "Error handling functionality that is shared between libloot's FFI wrappers."
publish = false
version.workspace = true
repository.workspace = true
edition.workspace = true
license.workspace = true

[lints]
workspace = true
